[package]
name = "macroex-extras"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroex = { version = "0.1.3", default-features = false }
quote = { version = "1.0.33", default-features = false }
